### PR TITLE
Java 21 migration branch

### PR DESCRIPTION
**Pull request by zrahman-ch**

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by chillier-ch — APPROVED** [review]

**Review by foman-ch — APPROVED** [review]

**Pull request merged**
